// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

`timescale 1 ns / 1 ps


`timescale 1 ns / 1 ps
module matrix_multiply_tbkb_pirdsp(
    din0_0,
    din0_1,
    din0_2,
    din1_0,
    din1_1,
    din1_2,
    dout0,
    dout1);

parameter ID = 32'd1;
parameter NUM_STAGE = 32'd1;
parameter din0_WIDTH = 32'd1;
parameter din1_WIDTH = 32'd1;
parameter din2_WIDTH = 32'd1;
parameter dout_WIDTH = 32'd1;
input[din0_WIDTH - 1:0] din0_0;
input[din1_WIDTH - 1:0] din0_1;
input[din2_WIDTH - 1:0] din0_2;
output[dout_WIDTH - 1:0] dout0;

input[din0_WIDTH - 1:0] din1_0;
input[din1_WIDTH - 1:0] din1_1;
input[din2_WIDTH - 1:0] din1_2;
output[dout_WIDTH - 1:0] dout1;



matrix_multiply_tbkb_pirdsp_0 matrix_multiply_tbkb_pirdsp_0_U(
    .in0_0( din0_0 ),
    .in0_1( din0_1 ),
    .in0_2( din0_2 ),
    .dout0( dout0 ),

    .in1_0( din1_0 ),
    .in1_1( din1_1 ),
    .in1_2( din1_2 ),
    .dout1( dout1 ));

endmodule

`timescale 1 ns / 1 ps

module matrix_multiply_tbkb_pirdsp_0(
    input  [8 - 1:0] in0_0,
    input  [8 - 1:0] in0_1,
    input  [8 - 1:0] in0_2,
    output [8 - 1:0]  dout0,
    input  [8 - 1:0] in1_0,
    input  [8 - 1:0] in1_1,
    input  [8 - 1:0] in1_2,
    output [8 - 1:0]  dout1);

wire signed [27 - 1:0]     a0;
wire signed [27 - 1:0]     b0;
wire signed [27 - 1:0]     a1;
wire signed [27 - 1:0]     b1;
wire signed [48 - 1:0]     c;
wire signed [45 - 1:0]     m;
wire signed [48 - 1:0]     p;

assign a0  = $signed(in0_0);
assign b0  = $signed(in0_1);

assign a1  = $signed(in1_0);
assign b1  = $signed(in1_1);

assign c  ={16'b0,in1_2,16'b0,in0_2};

wire [53:0] A;
wire [53:0] B;

assign A ={a1,a0};
assign B ={b1,b0};

MULT54X54 inst(
    .A(A),
    .B(B),
    .Y(m)
);

assign p  = m + c;

assign dout0 = p[7:0];

assign dout1 = p[31:24];

endmodule

/*
(* techmap_celltype = "$mul $__mul $__MULT9X9" *)
module MULT54X54(
        input [53:0] A,
        input [53:0] B,
        output [44:0] Y
 );

wire signed [17:0] C_0;
wire signed [17:0] C_1;
wire signed [17:0] C_2;
wire signed [17:0] C_3;
wire signed [17:0] C_4;
wire signed [17:0] C_5;

wire signed [8:0] A_0 = A[8:0];
wire signed [8:0] B_0 = B[8:0];
wire signed [8:0] A_1 = A[17:9];
wire signed [8:0] B_1 = B[17:9];
wire signed [8:0] A_2 = A[26:18];
wire signed [8:0] B_2 = B[26:18];
wire signed [8:0] A_3 = A[35:27];
wire signed [8:0] B_3 = B[35:27];
wire signed [8:0] A_4 = A[44:36];
wire signed [8:0] B_4 = B[44:36];
wire signed [8:0] A_5 = A[53:45];
wire signed [8:0] B_5 = B[53:45];

assign C_0 = A_0 * B_0;
assign C_1 = A_1 * B_1;
assign C_2 = A_2 * B_2;
assign C_3 = A_3 * B_3;
assign C_4 = A_4 * B_4;
assign C_5 = A_5 * B_5;

assign Y[44:24] = C_5 + C_4 + C_3;
assign Y[23:0] = C_2 + C_1 + C_0;

endmodule

*/